from __future__ import annotations

from datetime import datetime

from pydantic import Field

from schemas._compat import CompatBaseModel


class RouteHealthReport(CompatBaseModel):
    """Daily health summary for a protocol, chain, or bridge route.

    Audience: protocol operators, DAO treasuries, L2 teams — not trading agents.
    health_score is computed deterministically from signal ratios; summary is
    LLM-generated by RouteHealthAgent.
    """

    id: str | None = None
    # e.g. "AAVE", "Base", "Arbitrum", "Wormhole"
    protocol_or_chain: str
    # "protocol" | "chain" | "bridge"
    report_scope: str
    # 0.0 = maximum hazard/closure; 1.0 = fully healthy, growing traffic.
    health_score: float = Field(ge=0.0, le=1.0)
    # "growing" | "stable" | "declining"
    traffic_trend: str
    congestion_level: str  # RiskLevel value
    hazard_level: str      # RiskLevel value
    route_emergence_count: int = Field(default=0, ge=0)
    route_closure_count: int = Field(default=0, ge=0)
    dominant_inflow_source: str | None = None
    dominant_outflow_destination: str | None = None
    supporting_signal_ids: list[str] = Field(default_factory=list)
    summary: str
    created_by_agent: str
    created_at: datetime
